addSbtPlugin("org.scala-js"     % "sbt-scalajs"         % "1.6.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.8.1")
addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates"         % "0.5.3")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.3")
